### ISSUE TITLE
Attribute error for run code from example

### ISSUE THREAD

**Issue by no111u3** [analogdevicesinc/pyadi-iio#462]
Try from Pluto example (Mac OS 13.5, M2, arm64)
```
>>> import adi
>>> sdr = adi.Pluto('ip:pluto.local')
>>> sdr.rx_lo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/adi/ad936x.py", line 193, in rx_lo
    return self._get_iio_attr("altvoltage0", "frequency", True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/adi/attribute.py", line 127, in _get_iio_attr
    self._get_iio_attr_str(channel_name, attr_name, output, _ctrl)
  File "/opt/homebrew/lib/python3.11/site-packages/adi/attribute.py", line 122, in _get_iio_attr_str
    return channel.attrs[attr_name].value
           ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'frequency'
```

**Comment by tfcollins** [comment]
This is a known issue with the libiio python bindings. There is a related issue here: https://github.com/analogdevicesinc/libiio/issues/871

The development team doesn't have Apple Silicon machines so think is hard for us to debug at the moment. If you can get the requested information from the issue it would be helpful.

-Travis

**Comment by no111u3** [comment]
First of all, thanks for your fast answer.
For the begin I get info from iio_info for check how it works (I already use this library in sdrangel software and it works good):
```
% iio_info -u 'ip:pluto.local'
Library version: 0.23 (git tag: v0.23)
Compiled with backends: xml ip usb
IIO context created with network backend.
Backend version: 0.24 (git tag: v0.24)
Backend description string: 192.168.2.1 Linux (none) 5.10.0-98231-g9dfba10b795d #54 SMP PREEMPT Mon Jul 11 14:38:48 CEST 2022 armv7l
IIO context has 9 attributes:
	hw_model: Analog Devices PlutoSDR Rev.C (Z7010-AD9364)
	hw_model_variant: 1
	hw_serial: 10447376de0b000e00001f00e99f99a2f0
	fw_version: v0.35
	ad9361-phy,xo_correction: 40000046
	ad9361-phy,model: ad9364
	local,kernel: 5.10.0-98231-g9dfba10b795d
	uri: ip:pluto.local
	ip,ip-addr: 192.168.2.1
IIO context has 4 devices:
	iio:device0: ad9361-phy
		9 channels found:
			altvoltage1: TX_LO (output)
			8 channel-specific attributes found:
				attr  0: external value: 0
				attr  1: fastlock_load value: 0
				attr  2: fastlock_recall ERROR: Invalid argument (22)
				attr  3: fastlock_save value: 0 181,181,181,181,181,181,181,181,181,181,181,181,181,181,181,181
				attr  4: fastlock_store value: 0
				attr  5: frequency value: 2450000000
				attr  6: frequency_available value: [46875001 1 6000000000]
				attr  7: powerdown value: 0
			voltage0:  (input)
			15 channel-specific attributes found:
				attr  0: bb_dc_offset_tracking_en value: 1
				attr  1: filter_fir_en value: 0
				attr  2: gain_control_mode value: slow_attack
				attr  3: gain_control_mode_available value: manual fast_attack slow_attack hybrid
				attr  4: hardwaregain value: 46.000000 dB
				attr  5: hardwaregain_available value: [-1 1 73]
				attr  6: quadrature_tracking_en value: 1
				attr  7: rf_bandwidth value: 1500000
				attr  8: rf_bandwidth_available value: [200000 1 56000000]
				attr  9: rf_dc_offset_tracking_en value: 1
				attr 10: rf_port_select value: A_BALANCED
				attr 11: rf_port_select_available value: A_BALANCED B_BALANCED C_BALANCED A_N A_P B_N B_P C_N C_P TX_MONITOR1 TX_MONITOR2 TX_MONITOR1_2
				attr 12: rssi value: 68.00 dB
				attr 13: sampling_frequency value: 4000000
				attr 14: sampling_frequency_available value: [2083333 1 61440000]
			voltage3:  (output)
			8 channel-specific attributes found:
				attr  0: filter_fir_en value: 0
				attr  1: raw value: 306
				attr  2: rf_bandwidth value: 18000000
				attr  3: rf_bandwidth_available value: [200000 1 40000000]
				attr  4: rf_port_select_available value: A B
				attr  5: sampling_frequency value: 4000000
				attr  6: sampling_frequency_available value: [2083333 1 61440000]
				attr  7: scale value: 1.000000
			altvoltage0: RX_LO (output)
			8 channel-specific attributes found:
				attr  0: external value: 0
				attr  1: fastlock_load value: 0
				attr  2: fastlock_recall ERROR: Invalid argument (22)
				attr  3: fastlock_save value: 0 59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59
				attr  4: fastlock_store value: 0
				attr  5: frequency value: 92400000
				attr  6: frequency_available value: [70000000 1 6000000000]
				attr  7: powerdown value: 0
			voltage2:  (output)
			8 channel-specific attributes found:
				attr  0: filter_fir_en value: 0
				attr  1: raw value: 306
				attr  2: rf_bandwidth value: 18000000
				attr  3: rf_bandwidth_available value: [200000 1 40000000]
				attr  4: rf_port_select_available value: A B
				attr  5: sampling_frequency value: 4000000
				attr  6: sampling_frequency_available value: [2083333 1 61440000]
				attr  7: scale value: 1.000000
			temp0:  (input)
			1 channel-specific attributes found:
				attr  0: input value: 38596
			voltage0:  (output)
			10 channel-specific attributes found:
				attr  0: filter_fir_en value: 0
				attr  1: hardwaregain value: -10.000000 dB
				attr  2: hardwaregain_available value: [-89.750000 0.250000 0.000000]
				attr  3: rf_bandwidth value: 18000000
				attr  4: rf_bandwidth_available value: [200000 1 40000000]
				attr  5: rf_port_select value: A
				attr  6: rf_port_select_available value: A B
				attr  7: rssi value: 0.00 dB
				attr  8: sampling_frequency value: 4000000
				attr  9: sampling_frequency_available value: [2083333 1 61440000]
			voltage2:  (input)
			13 channel-specific attributes found:
				attr  0: bb_dc_offset_tracking_en value: 1
				attr  1: filter_fir_en value: 0
				attr  2: gain_control_mode_available value: manual fast_attack slow_attack hybrid
				attr  3: offset value: 57
				attr  4: quadrature_tracking_en value: 1
				attr  5: raw value: 928
				attr  6: rf_bandwidth value: 1500000
				attr  7: rf_bandwidth_available value: [200000 1 56000000]
				attr  8: rf_dc_offset_tracking_en value: 1
				attr  9: rf_port_select_available value: A_BALANCED B_BALANCED C_BALANCED A_N A_P B_N B_P C_N C_P TX_MONITOR1 TX_MONITOR2 TX_MONITOR1_2
				attr 10: sampling_frequency value: 4000000
				attr 11: sampling_frequency_available value: [2083333 1 61440000]
				attr 12: scale value: 0.305250
			out:  (input, WARN:iio_channel_get_type()=UNKNOWN)
			1 channel-specific attributes found:
				attr  0: voltage_filter_fir_en value: 0
		18 device-specific attributes found:
				attr  0: calib_mode value: auto
				attr  1: calib_mode_available value: auto manual manual_tx_quad tx_quad rf_dc_offs rssi_gain_step
				attr  2: dcxo_tune_coarse ERROR: Operation not supported by device (19)
				attr  3: dcxo_tune_coarse_available value: [0 0 0]
				attr  4: dcxo_tune_fine ERROR: Operation not supported by device (19)
				attr  5: dcxo_tune_fine_available value: [0 0 0]
				attr  6: ensm_mode value: fdd
				attr  7: ensm_mode_available value: sleep wait alert fdd pinctrl pinctrl_fdd_indep
				attr  8: filter_fir_config value: FIR Rx: 64,1 Tx: 64,1
				attr  9: gain_table_config value: <gaintable AD9361 type=FULL dest=3 start=0 end=1300000000>
-1, 0x00, 0x00, 0x20
// removed for readability 
73, 0x6F, 0x38, 0x20
</gaintable>
				attr 10: multichip_sync ERROR: Permission denied (13)
				attr 11: rssi_gain_step_error value: lna_error: 0 0 0 0
mixer_error: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
gain_step_calib_reg_val: 0 0 0 0 0
				attr 12: rx_path_rates value: BBPLL:1024000009 ADC:32000000 R2:16000000 R1:8000000 RF:4000000 RXSAMP:4000000
				attr 13: trx_rate_governor value: nominal
				attr 14: trx_rate_governor_available value: nominal highest_osr
				attr 15: tx_path_rates value: BBPLL:1024000009 DAC:32000000 T2:16000000 T1:8000000 TF:4000000 TXSAMP:4000000
				attr 16: xo_correction value: 40000046
				attr 17: xo_correction_available value: [39992046 1 40008046]
		182 debug attributes found:
				debug attr  0: digital_tune value: 0
				/// removed for readability 
				debug attr 181: direct_reg_access value: 0x0
		No trigger on this device
	iio:device1: xadc
		10 channels found:
			voltage5: vccoddr (input)
			2 channel-specific attributes found:
				attr  0: raw value: 1849
				attr  1: scale value: 0.732421875
			voltage0: vccint (input)
			2 channel-specific attributes found:
				attr  0: raw value: 1385
				attr  1: scale value: 0.732421875
			voltage4: vccpaux (input)
			2 channel-specific attributes found:
				attr  0: raw value: 2452
				attr  1: scale value: 0.732421875
			temp0:  (input)
			3 channel-specific attributes found:
				attr  0: offset value: -2219
				attr  1: raw value: 2704
				attr  2: scale value: 123.040771484
			voltage7: vrefn (input)
			2 channel-specific attributes found:
				attr  0: raw value: 2
				attr  1: scale value: 0.732421875
			voltage1: vccaux (input)
			2 channel-specific attributes found:
				attr  0: raw value: 2454
				attr  1: scale value: 0.732421875
			voltage2: vccbram (input)
			2 channel-specific attributes found:
				attr  0: raw value: 1383
				attr  1: scale value: 0.732421875
			voltage3: vccpint (input)
			2 channel-specific attributes found:
				attr  0: raw value: 1381
				attr  1: scale value: 0.732421875
			voltage8:  (input)
			2 channel-specific attributes found:
				attr  0: raw value: 3306
				attr  1: scale value: 0.244140625
			voltage6: vrefp (input)
			2 channel-specific attributes found:
				attr  0: raw value: 1706
				attr  1: scale value: 0.732421875
		1 device-specific attributes found:
				attr  0: sampling_frequency value: 961538
		No trigger on this device
	iio:device2: cf-ad9361-dds-core-lpc (buffer capable)
		6 channels found:
			voltage0:  (output, index: 0, format: le:S16/16>>0)
			4 channel-specific attributes found:
				attr  0: calibphase value: 0.000000
				attr  1: calibscale value: 1.000000
				attr  2: sampling_frequency value: 4000000
				attr  3: sampling_frequency_available value: 4000000 500000
			voltage1:  (output, index: 1, format: le:S16/16>>0)
			4 channel-specific attributes found:
				attr  0: calibphase value: 0.000000
				attr  1: calibscale value: 1.000000
				attr  2: sampling_frequency value: 4000000
				attr  3: sampling_frequency_available value: 4000000 500000
			altvoltage3: TX1_Q_F2 (output)
			5 channel-specific attributes found:
				attr  0: frequency value: 3999511
				attr  1: phase value: 0
				attr  2: raw value: 1
				attr  3: sampling_frequency value: 4000000
				attr  4: scale value: 0.000000
			altvoltage1: TX1_I_F2 (output)
			5 channel-specific attributes found:
				attr  0: frequency value: 3999511
				attr  1: phase value: 90000
				attr  2: raw value: 1
				attr  3: sampling_frequency value: 4000000
				attr  4: scale value: 0.000000
			altvoltage0: TX1_I_F1 (output)
			5 channel-specific attributes found:
				attr  0: frequency value: 3999511
				attr  1: phase value: 90000
				attr  2: raw value: 1
				attr  3: sampling_frequency value: 4000000
				attr  4: scale value: 0.000000
			altvoltage2: TX1_Q_F1 (output)
			5 channel-specific attributes found:
				attr  0: frequency value: 3999511
				attr  1: phase value: 0
				attr  2: raw value: 1
				attr  3: sampling_frequency value: 4000000
				attr  4: scale value: 0.000000
		2 device-specific attributes found:
				attr  0: sync_start_enable value: arm
				attr  1: sync_start_enable_available value: arm
		2 buffer-specific attributes found:
				attr  0: data_available value: 0
				attr  1: length_align_bytes value: 8
		1 debug attributes found:
				debug attr  0: direct_reg_access value: 0x90162
		No trigger on this device
	iio:device3: cf-ad9361-lpc (buffer capable)
		2 channels found:
			voltage0:  (input, index: 0, format: le:S12/16>>0)
			7 channel-specific attributes found:
				attr  0: calibbias value: 0
				attr  1: calibphase value: 0.000000
				attr  2: calibscale value: 1.000000
				attr  3: label ERROR: Socket operation on non-socket (38)
				attr  4: samples_pps ERROR: Operation not supported by device (19)
				attr  5: sampling_frequency value: 4000000
				attr  6: sampling_frequency_available value: 4000000 500000
			voltage1:  (input, index: 1, format: le:S12/16>>0)
			7 channel-specific attributes found:
				attr  0: calibbias value: 0
				attr  1: calibphase value: 0.000000
				attr  2: calibscale value: 1.000000
				attr  3: label ERROR: Socket operation on non-socket (38)
				attr  4: samples_pps ERROR: Operation not supported by device (19)
				attr  5: sampling_frequency value: 4000000
				attr  6: sampling_frequency_available value: 4000000 500000
		2 device-specific attributes found:
				attr  0: sync_start_enable value: disarm
				attr  1: sync_start_enable_available value: arm
		2 buffer-specific attributes found:
				attr  0: data_available value: 0
				attr  1: length_align_bytes value: 8
		2 debug attributes found:
				debug attr  0: pseudorandom_err_check value: CH0 : PN9 : Out of Sync : PN Error
CH1 : PN9 : Out of Sync : PN Error
				debug attr  1: direct_reg_access value: 0x0
		No trigger on this device
```

**Comment by no111u3** [comment]
Than I try to reach out by `iio_attr` it also accessibly:
```
% iio_attr -u 'ip:pluto.local' -c 'ad9361-phy' 'altvoltage0' 'frequency'
2399999998
```
But in python I reach out another result:
```python3
>>> import iio
>>> ctx = iio.Context('ip:pluto.local')
>>> ctx.devices[0].name
'ad9361-phy'
>>> ctx.devices[0].channels[0].name
'RX_LO'
>>> ctx.devices[0].channels[0].attrs
{'external': <iio.ChannelAttr object at 0x100e17e50>}
```

**Comment by no111u3** [comment]
Also I suppose that only one attribute for each channel got:
```
>>> for dev in ctx.devices:
...     for chan in dev.channels:
...             attrs_count = len(chan.attrs)
...             print(f'{dev.name}: {chan.name}: {attrs_count}')
...
ad9361-phy: RX_LO: 1
ad9361-phy: TX_LO: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
xadc: None: 1
xadc: vccint: 1
xadc: vccaux: 1
xadc: vccbram: 1
xadc: vccpint: 1
xadc: vccpaux: 1
xadc: vccoddr: 1
xadc: vrefp: 1
xadc: vrefn: 1
xadc: None: 1
cf-ad9361-dds-core-lpc: TX1_I_F1: 1
cf-ad9361-dds-core-lpc: TX1_I_F2: 1
cf-ad9361-dds-core-lpc: TX1_Q_F1: 1
cf-ad9361-dds-core-lpc: TX1_Q_F2: 1
cf-ad9361-dds-core-lpc: None: 1
cf-ad9361-dds-core-lpc: None: 1
cf-ad9361-lpc: None: 1
cf-ad9361-lpc: None: 1
```

**Comment by no111u3** [comment]
I added debug to channel constructor:
```python3
print([
                _c_get_attr(_channel, x).decode("ascii")
                for x in range(0, _c_attr_count(_channel))
            ])
```
And got strange output:
```python3
['external', 'external', 'external', 'external', 'external', 'external', 'external', 'external']
['bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en']
['filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en']
['external', 'external', 'external', 'external', 'external', 'external', 'external', 'external']
['filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en']
['input']
['filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en', 'filter_fir_en']
['bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en', 'bb_dc_offset_tracking_en']
['voltage_filter_fir_en']
ad9361-phy: RX_LO: 1
ad9361-phy: TX_LO: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
ad9361-phy: None: 1
```

**Comment by no111u3** [comment]
This issue generates by wrong bindings signatures fixed by https://github.com/analogdevicesinc/libiio/commit/1246cb031728f4958cfb4324678f600e637bf21c

**Comment by no111u3** [comment]
@tfcollins please look at my investigation, I think I found the main issue and possible solution.

**Comment by tfcollins** [comment]
If you use the iio.py from the libiio master branch does it resolve the issue?

**Comment by no111u3** [comment]
Yes sure, it fully resolve my issue

**Comment by tfcollins** [comment]
kk thanks for checking. I'll be creating the python release soon for v0.25 and we'll update the pyadi-iio dependencies
