### ISSUE TITLE
CN0540 can't read sensor_voltage after rx() call

### ISSUE THREAD

**Issue by WyattBreitner** [analogdevicesinc/pyadi-iio#465]
Version `0.0.15`

Steps to reproduce:
```
>>> import adi
>>> adc = adi.cn0540.cn0540(uri='ip:localhost')
>>> adc.sensor_voltage
2253.4198167155773
>>> adc.rx()
array([-2097152,    57839,    57839, ...,    57839,    57839,    57839])
>>> adc.sensor_voltage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/adi/cn0540.py", line 122, in sensor_voltage
    raw = self._get_iio_attr("voltage0", "raw", False, adc_chan)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/adi/attribute.py", line 156, in _get_iio_attr
    self._get_iio_attr_str(channel_name, attr_name, output, _ctrl)
  File "/usr/lib/python3.11/site-packages/adi/attribute.py", line 151, in _get_iio_attr_str
    return channel.attrs[attr_name].value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/iio.py", line 711, in <lambda>
    lambda self: self._read(),
                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/iio.py", line 740, in _read
    _c_read_attr(self._channel, self._name_ascii, buf, len(buf))
  File "/usr/lib/python3.11/site-packages/iio.py", line 62, in _check_negative
    raise OSError(-result, _strerror(-result))
OSError: [Errno 16] Device or resource busy
```

Setup is running on a DE10-Nano with:
Linux-adi `5.10`
libiio `0.23`
python `3.11.2`

**Comment by WyattBreitner** [comment]
Same misunderstanding as #466
