### ISSUE TITLE
No Device Found OS Error [Errno 78]

### ISSUE THREAD

**Issue by Caddis03** [analogdevicesinc/pyadi-iio#552]
Running python example script on Mac and I keep getting this error:

Traceback (most recent call last):
  File "/Users/calebaddis/radioconda/lib/python3.10/site-packages/adi/context_manager.py", line 36, in __init__
    self._ctx = iio.Context(self.uri)
  File "/Users/calebaddis/radioconda/lib/python3.10/site-packages/iio.py", line 1328, in __init__
    self._context = _new_uri(_context.encode("ascii"))
  File "/Users/calebaddis/radioconda/lib/python3.10/site-packages/iio.py", line 56, in _check_null
    raise OSError(err, _strerror(err))
OSError: [Errno 78] Function not implemented

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/calebaddis/Desktop/work/RF_Site_Survey/scan.py", line 13, in <module>
    sdr = adi.Pluto("local:")
  File "/Users/calebaddis/radioconda/lib/python3.10/site-packages/adi/rx_tx.py", line 718, in __init__
    rx_def.__init__(self, *args, **kwargs)
  File "/Users/calebaddis/radioconda/lib/python3.10/site-packages/adi/rx_tx.py", line 637, in __init__
    shared_def.__init__(self, *args, **kwargs)
  File "/Users/calebaddis/radioconda/lib/python3.10/site-packages/adi/rx_tx.py", line 587, in __init__
    context_manager.__init__(self, uri_ctx, self._device_name)
  File "/Users/calebaddis/radioconda/lib/python3.10/site-packages/adi/context_manager.py", line 38, in __init__
    raise Exception("No device found")
Exception: No device found

**Comment by tfcollins** [comment]
> sdr = adi.Pluto("local:")

You are using a local context which assumes you are running on the device itself (Pluto). Change to a USB or IP context on your mac: https://analogdevicesinc.github.io/pyadi-iio/guides/connectivity.html
